### ISSUE TITLE
Error when run php artisan tomato:generate in laravel 11

### ISSUE THREAD

**Issue by pandigresik** [tomatophp/tomato-model-generator#1]
I think this error because laravel 11 remove doctrine/dbal package https://laravel.com/docs/11.x/upgrade#doctrine-dbal-removal

`ahmad@ahmad-Lenovo-ideapad-300-14ISK:/data/docker/laravel/tomato$ php artisan tomato:generate

   BadMethodCallException 

  Method Illuminate\Database\MySqlConnection::getDoctrineSchemaManager does not exist.

  at vendor/laravel/framework/src/Illuminate/Macroable/Traits/Macroable.php:112
    108▕      */
    109▕     public function __call($method, $parameters)
    110▕     {
    111▕         if (! static::hasMacro($method)) {
  ➜ 112▕             throw new BadMethodCallException(sprintf(
    113▕                 'Method %s::%s does not exist.', static::class, $method
    114▕             ));
    115▕         }
    116▕ 

  i   Bad Method Call: Did you mean Illuminate\Database\MySqlConnection::getSchemaGrammar() ? 

      +2 vendor frames 

  3   [internal]:0
      Krlove\EloquentModelGenerator\TypeRegistry::__construct()
      +15 vendor frames 

  19  [internal]:0
      Illuminate\Container\Container::Illuminate\Container\{closure}()`

**Comment by fadymondy** [comment]
yes the package not support Laravel 11
